baseURL = "https://hugo-demo-b7su.onrender.com/"
languageCode = "en-us"
title = "Sekolah Koding Millenial"
theme = "skoding"
summaryLength = 10
paginate = 2
[params]
    Description = "tempat belajar koding"